# Generated by Django 4.2.17 on 2025-05-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='canceled_by_coach',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
