# Generated by Django 4.2.17 on 2025-04-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prajnayana_dashboard', '0013_habittracking_user_alter_visionboard_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('Affirmation', 'Affirmations'), ('Quote', 'Quote'), ('Win', 'Win'), ('CBT', 'Cbt')], max_length=255)),
                ('summary', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
